### ISSUE TITLE
Διόρθωση CSS στο navbar

### ISSUE THREAD

**Issue by NikolasPpd** [NikolasPpd/RaceHunter-Front-End#14]
Η CSS του navbar χρειάζεται διορθώσεις για να συμβαδίζει με τις προδιαγραφές των mockups.

Ειδικότερα, πρέπει:

- Ανεξαρτήτως width σελίδας, το logo θα είναι τέρμα αριστερά, το search bar στη μέση και τα κουμπιά `Αρχική/Σύνδεση` τέρμα δεξιά.
- Τα text fields στη μπάρα αναζήτησης θέλουν αλλαγές στο padding τους.
- Το κουμπί `Σύνδεση` πρέπει να έχει `border-radius: 30px;` και `cursor: pointer;` on hover.
- Η σκιά να αλλάξει (CSS στο Figma)
- Αυτή τη στιγμή μπαίνουν κενές γραμμές στην αρχή του περιεχομένου κάθε σελίδας για να μην κρύβεται από το navbar. Να γίνει sticky ώστε να μη χρειάζονται αυτά τα κενά.

**Comment by N10beP** [comment]
Υπάρχουν κάπου διαθέσιμα τα mockups για να χρησιμοποιηθούν ως reference?

**Comment by NikolasPpd** [comment]
Ναι: https://www.figma.com/file/5AntdEHvuAKqoVZHOQ64kF/Runner-App-Landing-Page
