### ISSUE TITLE
Δημιουργία σελίδας "Σχετικά με εμάς"

### ISSUE THREAD

**Issue by NikolasPpd** [NikolasPpd/RaceHunter-Front-End#8]
Δημιουργία σελίδας "Σχετικά με εμάς" σύμφωνα με τα mockups.

**Comment by N10beP** [comment]
Θα με ενδιέφερε να ασχοληθώ με αυτό το issue

**Comment by NikolasPpd** [comment]
Κανένα πρόβλημα. Ακόμα δεν έχουμε καταλήξει απόλυτα στο τι θα συμπεριλαμβάνεται στη συγκεκριμένη σελίδα, οπότε οι εικόνες που έχει και τα κείμενα είναι προσωρινά.
